inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0

  Exclude:
    - 'appveyor.yml'
    - 'Vagrantfile'
    - 'scripts/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/Encoding:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 25
